language: java
jdk:
  - oraclejdk7
before_install:
    - sudo apt-get install mysql-server -y
    - sudo service mysql restart
    - echo hibernate.current_session_context_class=thread > md-dao/src/main/resources/db.properties
    - echo hibernate.transaction.factory_class=org.hibernate.transaction.JDBCTransactionFactory >> md-dao/src/main/resources/db.properties
    - echo hibernate.show_sql=false >> md-dao/src/main/resources/db.properties
    - echo hibernate.connection.driver_class=com.mysql.jdbc.Driver >> md-dao/src/main/resources/db.properties
    - echo "hibernate.connection.url=jdbc:mysql://localhost:3306/bdre?createDatabaseIfNotExist=true" >> md-dao/src/main/resources/db.properties
    - echo hibernate.connection.password= >> md-dao/src/main/resources/db.properties
    - echo hibernate.connection.username=root >> md-dao/src/main/resources/db.properties
    - echo hibernate.dialect=org.hibernate.dialect.MySQLDialect >> md-dao/src/main/resources/db.properties
    - echo hibernate.default_schema=bdre >> md-dao/src/main/resources/db.properties
    - cat md-dao/src/main/resources/db.properties
    - mysql -uroot -e "create database if not exists bdre"
    - mysql -uroot bdre < databases/mysql/ddls/drop_tables.sql
    - mysql -uroot bdre < databases/mysql/ddls/create_tables.sql
install: /bin/true
script:
    - mvn -s settings.xml validate -P hdp22
after_script:
    - cat /home/travis/build/WiproOpenSourcePractice/openbdre/md-dao/target/generated-sources/hibernate3/com/wipro/ats/bdre/md/dao/jpa/Weburlsdb.java
notifications:
    email:
        - $BUILD_NOTIFICATION_EMAIL
cache:
  directories:
    - $HOME/.m2
